services:
    poketcg.jmtntbang.com:
        container_name: poketcg.jmtntbang.com
        network_mode: bridge
        working_dir: /app
        ports:
            - 55002:80
        restart: always
        image: poketcg.jmtntbang.com:latest
