services:
  PokemonTCG-Collector:
        container_name: PokemonTCG-Collector
        network_mode: bridge
        working_dir: /app
        ports:
            - ${PORT}:80
        restart: always
        volumes:
          - ${CONFIG_DIR}:/app/server/config
        image: pokemontcg-collector:latest
